# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f88984c84a2f028c9d332bd7398e7a9237e842116969eb9be13e5ddbfae0dfe3c20befd42be8b448b66c3cf3b98d786cc5c2e9b9914752b255c8bfc55a412f2

test:
  secret_key_base: 2c3e87284cac83d4cd2a0b32b9e0c3e9aec22ff711ada0d24d23dd35fe176ec9946063b81c5df1c4ef1af39121d1324e861ef071d81bfd23e8f1051d27f87c8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
